models/Articles.php
<?php
/**
 * Created by PhpStorm.
 * User: MirlanDev
 * Date: 03.08.2019
 * Time: 20:59
 */

namespace app\models;


use yii\db\ActiveRecord;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;
class Articles extends ActiveRecord
{
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'modified',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function isOwner()
    {
        if (\Yii::$app->user->identity->getId() == $this->user_id)
            return true;
        return false;
    }

}

models/User.php
<?php
/**
 * Created by PhpStorm.
 * User: MirlanDev
 * Date: 02.08.2019
 * Time: 21:08
 */

namespace app\models;


use yii\db\ActiveRecord;
use Yii;
use yii\web\IdentityInterface;
use yii\db\Expression;
use yii\behaviors\TimestampBehavior;

class User extends ActiveRecord implements IdentityInterface
{
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created',
                'updatedAtAttribute' => 'modified',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    public static function tableName()
    {
        return 'users';
    }

    public function getArticles()
    {
        return $this->hasMany(Articles::className(), ['user_id' => 'id']);
    }

    public function isAdmin()
    {
        if ($this->role == 'admin')
            return true;
        return false;
    }

    public function setPassword($password)
    {
        $this->password = \Yii::$app->getSecurity()->generatePasswordHash($password);
    }

    public function validatePassword($password)
    {
//        print_die($password);
        return Yii::$app->getSecurity()->validatePassword($password, $this->password);
    }

    public static function findIdentity($id)
    {
        return self::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {

    }

    public function getId()
    {
        return $this->id;
    }

    public function getAuthKey()
    {

    }

    public function validateAuthKey($authKey)
    {

    }
}

controllers/ArticlesController.php
<?php
/**
 * Created by PhpStorm.
 * User: MirlanDev
 * Date: 03.08.2019
 * Time: 20:04
 */

namespace app\controllers;


use app\models\ArticleForm;
use app\models\Articles;
use app\models\User;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use Yii;
class ArticlesController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'add', 'view', 'edit', 'delete'],
                'rules' => [

                    [
                        'allow' => true,
                        'actions' => ['index', 'add', 'view', 'edit', 'delete'],
                        'roles' => ['@'],

                        'denyCallback' => function ($rule, $action) {
                            throw new \Exception('У вас нет доступа к этой странице');
                        }

                    ],

                ],

            ],
        ];
    }

    public function actionIndex()
    {
        $articles = null;
        $viewer = \Yii::$app->user->identity;

        if ($viewer->isAdmin())
            $articles = Articles::find()->with('author')->all();
        else
            $articles = Articles::find()->with('author')->where(['user_id' => $viewer->getId()])->all();
//        print_die($articles);
        $this->view->title = 'Список статей';
        return $this->render('index', compact('articles'));
    }

    public function actionView($id)
    {
        $id = (int)$id;
        $article = Articles::findOne($id);
        if (empty($article)) {
            throw new NotFoundHttpException('Статья не найдена');
        }

        if (!Yii::$app->user->identity->isAdmin() && !$article->isOwner()) {
            throw new ForbiddenHttpException('У вас нет доступа к этой странице');
        }
        $this->view->title = 'Просмотр статьи';
        return $this->render('view', compact('article'));
    }

    public function actionAdd()
    {
        $addForm = new ArticleForm();
        if ($addForm->load(\Yii::$app->request->post())) {
            if ($addForm->validate()) {

                if( $addForm->save()) {
                    Yii::$app->session->setFlash('success', "Статья успешно добавлена");
                } else
                    Yii::$app->session->setFlash('error', "Ошибка добавления статьи");
                return $this->redirect(['index']);
            }
        }
        $this->view->title = 'Добавление статьи';
        return $this->render('add', compact('addForm'));
    }

    public function actionEdit($id)
    {
        $this->view->title = 'Редактирование статьи';
        $id = (int)$id;
        $article = Articles::findOne($id);

        if (empty($article)) {
            throw new NotFoundHttpException('Статья не найдена');
        }
        if (!Yii::$app->user->identity->isAdmin() && !$article->isOwner()) {
            throw new ForbiddenHttpException('У вас нет доступа к этой странице', 403);
        }

        if (\Yii::$app->request->isAjax) {
            $this->layout = false;
        }

        $editForm = new ArticleForm();
        $editForm->setAttributes($article->toArray());
        if ($editForm->load(\Yii::$app->request->post())) {
            if ($editForm->validate()) {
                if ($editForm->save($article)) {
                    Yii::$app->session->setFlash('success', "Статья успешно отредактирована");
                } else
                    Yii::$app->session->setFlash('error', "Ошибка редактирования статьи");

                return $this->redirect(['index']);
            }
        }
        return $this->render('edit', compact('editForm'));
    }

    public function actionDelete($id)
    {
        $id = (int)$id;
        $article = Articles::findOne($id);
        if (empty($article)) {
            throw new NotFoundHttpException('Статья не найдена');
        }

        if (!Yii::$app->user->identity->isAdmin() && !$article->isOwner()) {
            throw new ForbiddenHttpException('У вас нет доступа к этой странице');
        }

        if ($article->delete())
            \Yii::$app->session->setFlash('success', 'Статья успешно удалена');
        else
            \Yii::$app->session->setFlash('error', 'Ошибка удаления статьи');

        return $this->redirect('index');
    }


}

controllers/UsersController.php
<?php
/**
 * Created by PhpStorm.
 * User: MirlanDev
 * Date: 02.08.2019
 * Time: 14:02
 */

namespace app\controllers;

use app\models\Articles;
use app\models\EditUserForm;
use yii\filters\AccessControl;
use app\models\LoginForm;
use app\models\SignupForm;
use app\models\User;
use yii\web\Controller;
use app\models\TestForm;
use yii\web\NotFoundHttpException;
use Yii;

class UsersController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['login', 'logout', 'signup', 'index', 'view', 'edit', 'add', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'signup'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['login', 'logout'],
                        'roles' => ['@'],
                    ],

                    [
                        'allow' => true,
                        'actions' => ['index', 'view', 'edit', 'add', 'delete'],
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Yii::$app->user->identity->isAdmin();
                        },
///                        'denyCallback' => function ($rule, $action) {
//                            throw new \Exception('У вас нет доступа к этой странице');
//                        }

                    ],

                ],

            ],
        ];
    }

    public function actionIndex()
    {
        $viewer = Yii::$app->user->identity;
        $users = User::find()
//            ->where('id != ' . $viewer->getId())
            ->all();

        $this->view->title = 'Список пользователей';
        return $this->render('index', compact('users'));
    }

    public function actionSignup()
    {
        $signUpForm = new SignupForm();
        if ($signUpForm->load(Yii::$app->request->post())) {
            if ($signUpForm->validate()) {
                Yii::$app->user->login($signUpForm->save());
                return $this->goHome();
            }
        }
        $this->view->title = "Регистрация";
        return $this->render('signup', compact('signUpForm'));
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest)
            $this->goHome();

        $loginForm = new LoginForm();

        if ($loginForm->load(Yii::$app->request->post())) {
            if ($loginForm->validate()) {
                Yii::$app->user->login($loginForm->getUser());
                $this->goHome();
//                print_die('validate');
            }
        }
        $this->view->title = "Авторизация";
        return $this->render('login', compact('loginForm'));
    }

    public function actionLogout()
    {
        if (!Yii::$app->user->isGuest) {
            Yii::$app->user->logout();
        }
        return $this->redirect(['login']);
    }

    public function actionDelete($id)
    {
        $id = (int)$id;
        $user = User::findOne($id);
        $viewer = \Yii::$app->user->identity;
        if (empty($user)) {
            throw new NotFoundHttpException('Пользователь не найден');
        }
        //Самоудаление
        if ($viewer->getId() == $user->id) {
            \Yii::$app->session->setFlash('error','Данное действие невозможно!');
            return $this->redirect(['index']);
        }

        //Удаление пользователя
        if ($user->delete()) {
            Articles::deleteAll(['user_id' => $user->id]);
            \Yii::$app->session->setFlash('success', "Пользователь $user->email успешно удален");
        }
        else
            \Yii::$app->session->setFlash('error', 'Ошибка удаления пользователя');

        return $this->redirect(['index']);
    }

    public function actionAdd()
    {
        $addForm = new SignupForm();
        if ($addForm->load(Yii::$app->request->post())) {
            if ($addForm->validate()) {
                if ($user = $addForm->save())
                    Yii::$app->session->setFlash('success', "Пользователь $user->email успешно добвален");
                else
                    Yii::$app->session->setFlash('error', 'Ошибка при добавлении пользователя');
                return $this->redirect(['index']);
            }
        }
        $this->view->title = 'Добавление пользвателя';
        return $this->render('add', compact('addForm'));
    }

    public function actionEdit($id)
    {
        $id = (int)$id;
        $user = User::findOne($id);
        $viewer = \Yii::$app->user->identity;

        if (empty($user)) {
            throw new NotFoundHttpException('Пользователь не найден');
        }

        $editForm = new EditUserForm();
        $userArr = $user->toArray();
        unset($userArr['password']);

        $editForm->setAttributes($userArr);
//        print_die($editForm->attributes);
        if ($editForm->load(Yii::$app->request->post())) {
            if ($editForm->validate()) {
                if ($user = $editForm->save($user))
                    Yii::$app->session->setFlash('success', "Пользователь $user->email успешно отредактирован");
                else
                    Yii::$app->session->setFlash('error', 'Ошибка при редактировании пользователя');
                return $this->redirect(['index']);
            }
        }

        $this->view->title = 'Редактирование пользователя';
        return $this->render('edit', compact('editForm'));
    }

    public function actionView($id)
    {
        $id = (int)$id;
        $user = User::findOne($id);

        if (empty($user)) {
            throw new NotFoundHttpException('Пользователь не найден');
        }
        $this->view->title = 'Просмотр пользователя';
        return $this->render('view', compact('user'));
    }

}

views/users/add.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->params['breadcrumbs'][] = $this->title;
?>

<div class="users-add">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php $form = ActiveForm::begin()?>
    <?= $form->field($addForm, 'email')->input('email') ?>
    <?= $form->field($addForm, 'name')?>
    <?= $form->field($addForm, 'password')->passwordInput() ?>
    <?= $form->field($addForm, 'password_repeat')->passwordInput() ?>
    <?= $form->field($addForm, 'role')->dropDownList(['user' => 'Пользователь', 'admin' => 'Администратор']) ?>
    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary'])?>
    <?php $form = ActiveForm::end()?>

</div>

views/users/edit.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->params['breadcrumbs'][] = $this->title;
?>

<div class="users-edit">
    <h1><?= Html::encode($this->title) ?></h1>
    <?php $form = ActiveForm::begin()?>
    <?= $form->field($editForm, 'id')->hiddenInput()->label(false) ?>
    <?= $form->field($editForm, 'email')->input('email') ?>
    <?= $form->field($editForm, 'name')?>
    <?= $form->field($editForm, 'password')->passwordInput() ?>
    <?= $form->field($editForm, 'password_repeat')->passwordInput() ?>
    <?= $form->field($editForm, 'role')->dropDownList(['user' => 'Пользователь', 'admin' => 'Администратор']) ?>
    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary'])?>
    <?php $form = ActiveForm::end()?>

<!--    --><?//= $this->registerCssFile('@web/js/script.js', ['depends' => [\yii\web\JqueryAsset::className()]]) ?>

</div>

views/users/index.php
<?php
use yii\helpers\Html;
$this->params['breadcrumbs'][] = $this->title;
?>
<?= Html::a('Добавить пользователя', ['add'])?>
<h1><?= Html::encode($this->title) ?></h1>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Id</th>
        <th scope="col">E-mail</th>
        <th scope="col">Имя</th>
        <th scope="col">Роль</th>
        <th scope="col">Создан</th>
        <th scope="col">Отредактирован</th>
        <th scope="col">Операции</th>
    </tr>
    </thead>
    <tbody>

    <?php foreach ($users as $user) { ?>
        <tr>
            <th scope="row"><?= $user->id ?></th>
            <td><?= Html::a(Html::encode($user->email), ['view', 'id' => $user->id]) ?></td>
            <td><?= Html::a(Html::encode($user->name), ['view', 'id' => $user->id]) ?></td>
            <td><?= Html::encode($user->role) ?></td>
            <td><?= $user->created ?></td>
            <td><?= $user->modified ?></td>
            <td><?= Html::a('Edit', ['edit', 'id' => $user->id])?>

                <?php echo Yii::$app->user->identity->getId() != $user->id ? ' | '. Html::a('Delete', ['delete', 'id' => $user->id]) : ''?></td>
        </tr>
    <?php }?>

    </tbody>
</table>

views/users/login.php
<?php
/**
 * Created by PhpStorm.
 * User: MirlanDev
 * Date: 03.08.2019
 * Time: 11:07
 */


/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, заполните следующие поля для входа:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?= $form->field($loginForm, 'email')->textInput(['autofocus' => true])->input('email') ?>

    <?= $form->field($loginForm, 'password')->passwordInput() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>


</div>

views/users/signup.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="users-signup">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>Пожалуйста, заполните следующие поля для регистрации:</p>
    <?php $form = ActiveForm::begin()?>
    <?= $form->field($signUpForm, 'email')->input('email') ?>
    <?= $form->field($signUpForm, 'name')?>
    <?= $form->field($signUpForm, 'password')->passwordInput() ?>
    <?= $form->field($signUpForm, 'password_repeat')->passwordInput() ?>
<!--    --><?//= $form->field($signUpForm, 'role')->dropDownList(['user' => 'Пользователь', 'admin' => 'Администратор']) ?>
    <?= Html::submitButton('Регистрация', ['class' => 'btn btn-primary'])?>
    <?php $form = ActiveForm::end()?>

</div>

views/users/view.php
<?php
use yii\helpers\Html;
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="users-view">
    <div class="contain">
        <h3 class="mt-5">Имя: <?= Html::encode($user->name) ?></h3>
        <h3 class="mt-5">E-mail: <?= Html::encode($user->email) ?></h3>

        <p>Дата регистрации: <?= $user->created ?></p>

        <p>Дата редактирования: <?= $user->modified ?></p>
        <p><?= Html::a('Назад к списку пользователей', ['index']) ?></p>
    </div>
    <p>Количество статей: <?= count($user->articles) ?></p>
    <?php if ($user->articles) { ?>
    <h1>Статьи</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Название</th>
            <th scope="col">Автор</th>
            <th scope="col">Создан</th>
            <th scope="col">Отредактирован</th>
            <th scope="col">Операции</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($user->articles as $article) { ?>
            <tr>
                <th scope="row"><?= $article->article_id ?></th>
                <td><?= Html::a(Html::encode($article->title), ['articles/view', 'id' => $article->article_id]) ?></td>
                <td><?= Html::encode(empty($article->author) ? 'deleted' : $article->author->email ) ?></td>
                <td><?= $article->created ?></td>
                <td><?= $article->modified ?></td>
                <td><?= Html::a('Edit', ['articles/edit', 'id' => $article->article_id])?> | <?= Html::a('Delete', ['articles/delete', 'id' => $article->article_id])?></td>
            </tr>
        <?php }?>

        </tbody>
    </table>
</div>
<?php } ?>